industry:
    path:     /
    defaults: { _controller: "CoreBundle:Industry:index" }

industry_show:
    path:     /{id}/show
    defaults: { _controller: "CoreBundle:Industry:show" }

industry_new:
    path:     /new
    defaults: { _controller: "CoreBundle:Industry:new" }

industry_create:
    path:     /create
    defaults: { _controller: "CoreBundle:Industry:create" }
    methods:  POST

industry_edit:
    path:     /{id}/edit
    defaults: { _controller: "CoreBundle:Industry:edit" }

industry_update:
    path:     /{id}/update
    defaults: { _controller: "CoreBundle:Industry:update" }
    methods:  [POST, PUT]

industry_delete:
    path:     /{id}/delete
    defaults: { _controller: "CoreBundle:Industry:delete" }
    methods:  [POST, DELETE]
